### ISSUE TITLE
auto save not working on org-mode

### ISSUE THREAD

**Issue by map7** [ChillarAnand/real-auto-save#20]
I have installed the latest (20150512 release) of real-auto-save and have added the following to my emacs 24.3.1 setup;

;; Automatically save the file
;; 
(require 'real-auto-save)
(add-hook 'org-mode-hook 'real-auto-save-mode)
(setq real-auto-save-interval 5)        ; in seconds

When I modify an org-mode file real-auto-save no longer auto saves.

**Comment by ChillarAnand** [comment]
@map7 thanks for the report. i have updated code. can you try the latest version and see if it works?

**Comment by map7** [comment]
Yes that new version works, thank you.
