### ISSUE TITLE
Suppress message in minibuffer when a buffer is saved

### ISSUE THREAD

**Issue by dylanmei** [ChillarAnand/real-auto-save#25]
Is there a way of hiding the `Wrote foo.bar` message when a buffer is saved?

I found [this article on emacs.stackexchange.com](http://emacs.stackexchange.com/questions/14706/suppress-message-in-minibuffer-when-a-buffer-is-saved) but I don't quite understand what the advice is.

I'm using emacs version 25.1.1.

**Comment by ChillarAnand** [comment]
@dylanmei  I tried couple of solutions. None of them worked for me. If I found anything that works, I will update here. Thanks.

**Comment by halueda** [comment]
You can use following
```
(defmacro with-suppressed-message (&rest body)
  "Suppress new messages temporarily in the echo area and the `*Messages*' buffer while BODY is evaluated."
  (declare (indent 0))
  (let ((message-log-max nil))
    `(with-temp-message (or (current-message) "") ,@body)))

(with-suppressed-message (save-buffer))
```

instead of (save-buffer)

This code comes from http://qiita.com/itiut@github/items/d917eafd6ab255629346 in Japanese.

**Comment by ChillarAnand** [comment]
Thanks @halueda. This works as expected. There is no need of `  (declare (indent 0))`. Would you like to send a PR for that?

**Comment by halueda** [comment]
I just copy&paste from Qiita page. I don't need PR for `(declare (indent 0))` .
Thanks.
