### ISSUE TITLE
Buffer name changes confuse the timers

### ISSUE THREAD

**Issue by flub** [ChillarAnand/real-auto-save#26]
When the buffer name changes the timers can no longer find the buffers and keep giving errors.  E.g. if you open: `~/foo/name`, enable real-auto-save, open `~/bar/name` now the original buffer name changed from `name` to `foo/name` and you get errors like: `Error running timer ‘real-auto-save-buffers’: (error "No buffer named name")` each time the timer expires.

**Comment by ChillarAnand** [comment]
@flub Thank you for the bug report. We need to add check for the existence of the buffer before saving.

**Comment by ChillarAnand** [comment]
Fixed in the latest version. Feel free to reopen if the problem persists. Thank you.

**Comment by flub** [comment]
Thanks for the quick fix!
