### ISSUE TITLE
Is it possible to toggle the behavior?

### ISSUE THREAD

**Issue by chrissound** [ChillarAnand/real-auto-save#28]
Rather than acting globally on all files all the time, can I conditionally enable it by calling a function?

Thanks!

**Comment by chrissound** [comment]
Seems it's possible by not adding this line: `(add-hook 'prog-mode-hook 'real-auto-save-mode)` which turns it on by default.

And instead calling `real-auto-save-mode` when needed.

**Comment by ChillarAnand** [comment]
Glad you found the solution. Feel free to open an issue if you face any problem.
