### ISSUE TITLE
Change timer to trigger on a duration after idle

### ISSUE THREAD

**Issue by TyOverby** [ChillarAnand/real-auto-save#32]
Right now I have an issue with real-auto-save:  I'll be typing, and in the middle of my typing, real-auto-save will kick in and save the buffer, triggering some other plugins that cause typing delays.

I would like instead for real-auto-save to save at some duration after emacs becomes idle.  That is, if no text has been written into the buffer for 1 second, then do an autosave.

**Comment by ChillarAnand** [comment]
Hi @TyOverby, that makes sense. I will look into this.

**Comment by jots** [comment]
I would love this feature as well.  I think it can also be called keyboard debouncing. (debouncer for future searchers)

**Comment by novoid** [comment]
I do have the very same issue: real-auto-save activates itself after the duration without taking into account that I'm currently interacting with emacs.

However, I do have **a different opinion on how to solve this** issue. In contrast to the suggestion above "real-auto-save after duration/x seconds of idle time" I would prefer an additional option resulting in following pseudo-code algorithm:

```
after configured real-auto-save-interval: 
   if current idle time is greater or equal than x seconds:
       real-auto-save buffers
   else:
       wait until idle time exceeds x seconds
       real-auto-save buffers
   endif
```

This way, the duration (`real-auto-save-interval`) is the _minimum_ amount of time that no real-auto-save kicks in. With this newly, second duration (in the example: `x`), I can configure emacs to wait until I'm not interacting with emacs for a certain period of time.

The advantage of this approach is that you can have 

1. the current behavior (`real-auto-save-interval`>0, x=0), 
2. the behavior as suggested above (`real-auto-save-interval`=0, x>0) as well as 
3. my scenario (`real-auto-save-interval`>0, x>0).

My personal preference is 300 seconds for duration (`real-auto-save-interval`) and it would be 10 seconds of idle time (`x`).

**Comment by novoid** [comment]
This seems to be related to #41

**Comment by ChillarAnand** [comment]
Thanks, @novoid 

This is fixed in the latest version. Please re-open if you face any issues.

**Comment by novoid** [comment]
Thanks @ChillarAnand for this improvement! I'll test over the next week.

For all the others, reading this in the future: the current patch introduced the original idea of choosing between:

1. save after strict $interval and
2. save after $interval of idle time

This reflects the original idea above and not my suggestion.

**Comment by conao3** [comment]
[EDIT] This comment has moved to https://github.com/ChillarAnand/real-auto-save/issues/43#issuecomment-620767231

---

After this change, all my CPU is full occupied by EMACS.
Are you have any suggestions?
Is it working well in your environment?

Run Emacs using below debug init.el and open `~/.debug.emacs.d/real-auto-save/init.el`, Emacs use 100% of one CPU.
```emacs-lisp
;; ~/.debug.emacs.d/real-auto-save/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(prog1 "prepare leaf"
  (prog1 "package"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize))

  (prog1 "leaf"
    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf))))

(leaf real-auto-save
  :ensure t
  :hook (find-file-hook)
  :config
  (real-auto-save-activate-advice))
```

Screenshots
![Screenshot_2020-04-29_02-26-48](https://user-images.githubusercontent.com/4703128/80519183-8cf8d580-89c2-11ea-968b-49990abece39.png)
![Screenshot_2020-04-29_02-26-31](https://user-images.githubusercontent.com/4703128/80519192-8f5b2f80-89c2-11ea-8fb3-923a952e6e73.png)
