### ISSUE TITLE
real-auto-save-silent is not defined

### ISSUE THREAD

**Issue by gergelypolonkai** [ChillarAnand/real-auto-save#39]
I set up auto save by enabling `real-auto-save-mode`. For a while i started getting this error:

    Error running timer ‘real-auto-save-buffers’: (void-variable real-auto-save-silent)

Looking at the code there is indeed no variable set with this name, only a customize group:

```
(defcustom real-auto-save-interval nil
  "Silent save of real auto save."
  :type 'convenience
  :group 'real-auto-save-silent)
```

Other than that, this name only appears in a condition in `real-auto-save-buffers`:

```
(if (not real-auto-save-silent)
    (with-suppressed-message (save-buffer))
  (let ((inhibit-message t)) (save-buffer)))
```

**Comment by conao3** [comment]
This error is caused by PR #37.
I think there is a simple misunderstanding in this PR.

https://github.com/ChillarAnand/real-auto-save/blob/9929bd26daf6b8902b1f2c01e7cc4f50fccee191/real-auto-save.el#L54-L62
```
(defcustom real-auto-save-interval 10
  "Time interval of real auto save."
  :type 'integer
  :group 'real-auto-save)

(defcustom real-auto-save-interval nil
  "Silent save of real auto save."
  :type 'convenience
  :group 'real-auto-save-silent)
```

**Comment by conao3** [comment]
When I investigate it, I think that suppression of messages by inhibit-message is better in the past implementations.
Headers that are not needed are included in the code, and I encourage you to simply revert this PR.
https://github.com/ChillarAnand/real-auto-save/pull/37/commits/810e4d80bc659f3f0a6b49b615752ae9ef1498ae#diff-c60c5bf84a449f45547c3bf84d50d914R9

**Comment by conao3** [comment]
This problem is solved. Close #39.

[edit]
oops. I can't do it. please.

**Comment by ChillarAnand** [comment]
Thanks @conao3 
@gergelypolonkai If you have any other issues, feel free to reopen.
