### ISSUE TITLE
Can this be easily set to an idle timer of 5 seconds so everytime emacs is idle it saves

### ISSUE THREAD

**Issue by JSpenced** [ChillarAnand/real-auto-save#41]

**Comment by ChillarAnand** [comment]
@JSpenced By default it saves after 10 seconds by default. You can customise this as mentioned here. https://github.com/ChillarAnand/real-auto-save#configuration

Does that help?

**Comment by JSpenced** [comment]
But it's a standard `run-with-timer` from looking at the code, right? You
have no option for `run-with-idle-timer`?

I only want it to run when emacs has been idle for 10 seconds, not every 10
seconds. I can probably rewrite the `defun` to do that but I didn't know if
you had a setting for that or not.

**Comment by ChillarAnand** [comment]
Makes sense. @JSpenced 

We can make idle timer save as default and provide another option in which users can override if they want to save every 10 seconds.

Would you like to send a patch for it?

**Comment by JSpenced** [comment]
I ended up writing my own configuration that just has a repeat `run-with-timer` every 30 minutes that starts a one time `run-with-idle-timer`, so it only activates after emacs is idle (also cancels the timer before it runs in case there was the same idle-timer already set but didn't run in the last 30 minutes. 

I really just wanted org-agenda buffers saved. There is already a command for that, so this was quick and easy to do.

If I get a chance or I start using this package, then I'll try to write a patch.

**Comment by ChillarAnand** [comment]
Thanks, @JSpenced 

This is fixed in the latest version.
